site_name: Beter Benutten Scan documentatie
site_url: https://retrofiteuropegroup.github.io/beterbenuttenscan-docs/
repo_url: https://github.com/RetrofitEuropeGroup/beterbenuttenscan-docs
repo_name: RetrofitEuropeGroup/beterbenuttenscan-docs
nav:
  - BeterBenuttenScan:
      - beterbenuttenscan/index.md
      - Gebouwtypes:
          - Appartementencomplexen: beterbenuttenscan/gebouwtypes/appartementencomplexen.md
          - Hoekwoningen: beterbenuttenscan/gebouwtypes/hoekwoningen.md
      - Filteren: beterbenuttenscan/filteren.md
      - Wegen: beterbenuttenscan/wegen/index.md
      - Analyseren:
          - BeterBenuttenScan: beterbenuttenscan/analyseren/beterbenuttenscan.md
          - Mobiliteit: beterbenuttenscan/analyseren/mobiliteit.md
          - Voorzieningen: beterbenuttenscan/analyseren/voorzieningen.md
          - Regelgeving: beterbenuttenscan/analyseren/regelgeving.md
          - Verstedelijking: beterbenuttenscan/analyseren/verstedelijking.md
          - Ondergrond: beterbenuttenscan/analyseren/ondergrond.md
          - Eigendomsinformatie: beterbenuttenscan/analyseren/eigendomsinformatie.md
          - Energietransitie: beterbenuttenscan/analyseren/energietransitie.md
          - Street view: beterbenuttenscan/analyseren/street-view.md
      - Exporteren: beterbenuttenscan/exporteren.md
      - Voorbeeld user story: beterbenuttenscan/voorbeeld-user-story.md
  - PIM platform:
      - pim-info/index.md
  - Workshops:
      - workshops/ondersteuning.md
  - Literatuur:
      - Literatuurbibliotheek: literatuur/literatuurbibliotheek.md
  - FAQ: faq.md
  - Over ons: over-ons/index.md
markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      locale: nl
      timezone: Europe/Amsterdam
      fallback_to_build_date: false
  - git-committers:
      repository: RetrofitEuropeGroup/beterbenuttenscan-docs
      branch: main
theme:
  name: material
  palette:
    primary: 'custom'
    accent: 'red'
  font:
    text: Arial
    code: Consolas
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.expand
    - content.tabs.link
extra_css:
  - stylesheets/bzk.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js